### ISSUE TITLE
Request to hijack lora just like a1111-sd-webui-locon

### ISSUE THREAD

**Issue by jimlin1668478052** [KohakuBlueleaf/a1111-sd-webui-lycoris#37]
Previously I used a1111-sd-webui-locon which hijack the built-in lora so that I can use <lora:...> for lycoris as well.

Now I change to a1111-sd-webui-lycoris because I found a bug in a1111-sd-webui-locon and found that the old package was used no more.

When I use <lyco:...> as specified in the readme file of the new package, I found that it cannot be recognized by other packages like composable lora (https://github.com/a2569875/stable-diffusion-webui-composable-lora).

So could you also hijack built-in lora for this package as the previous one? Thanks.

**Comment by KohakuBlueleaf** [comment]
No.
Hijack built-in lora will never be an option.
You can try to do it by yourself
And you will find out it is not a good idea.

Why I don't want to hijack built-in lora:
1, I need to know where is the built-in lora and add it into sys.path so I can import it, and this is basically impossible, since different environments may have some custom things.
2, I need to always catch up all the update from a1111
3, If user are using some other extension, just like conposable loras, it is very likely that I will get lot of issues from them.(And I did get tons of issues from other lora ext)
